parameters:
#    lampquiz.example.class: Websites\LampquizBundle\Example

services:
#    lampquiz.example:
#        class: %lampquiz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
